MotionCaptureRNN:
    trainer: ppo
    batch_size: 128
    beta: 5.0e-3
    buffer_size: 100
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 0.5e-4
    learning_rate_schedule: linear
    max_steps: 5.0e6
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 128
    summary_freq: 1000
    use_recurrent: true
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99